// Code generated by exported/generate/tagstests/main.go; DO NOT EDIT.

package timestreaminfluxdb_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/hashicorp/terraform-provider-aws/exported/acctest/statecheck"
	tftimestreaminfluxdb "github.com/hashicorp/terraform-provider-aws/exported/service/timestreaminfluxdb"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tftimestreaminfluxdb.ServicePackage(context.Background()), resourceAddress, knownValue)
}
