// Code generated by exported/generate/tagstests/main.go; DO NOT EDIT.

package bedrock_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/hashicorp/terraform-provider-aws/exported/acctest/statecheck"
	tfbedrock "github.com/hashicorp/terraform-provider-aws/exported/service/bedrock"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfbedrock.ServicePackage(context.Background()), resourceAddress, knownValue)
}
