// Code generated by exported/generate/tagstests/main.go; DO NOT EDIT.

package appconfig_test

import (
	"context"

	"github.com/hashicorp/terraform-plugin-testing/knownvalue"
	"github.com/hashicorp/terraform-plugin-testing/statecheck"
	tfstatecheck "github.com/hashicorp/terraform-provider-aws/exported/acctest/statecheck"
	tfappconfig "github.com/hashicorp/terraform-provider-aws/exported/service/appconfig"
)

func expectFullResourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullResourceTags(tfappconfig.ServicePackage(context.Background()), resourceAddress, knownValue)
}

func expectFullDataSourceTags(resourceAddress string, knownValue knownvalue.Check) statecheck.StateCheck {
	return tfstatecheck.ExpectFullDataSourceTags(tfappconfig.ServicePackage(context.Background()), resourceAddress, knownValue)
}
